export const skillStackType = [
  {
    id: 1,
    postStack: 'SPRING',
  },
  {
    id: 2,
    postStack: 'PYTHON',
  },
  {
    id: 3,
    postStack: 'KOTLIN',
  },
  {
    id: 4,
    postStack: 'C_PLUS_PLUS',
  },
  { id: 5, postStack: 'SPRING_BOOT' },
  { id: 6, postStack: 'JPA' },
  { id: 7, postStack: 'SPRING_JDBC' },
  { id: 8, postStack: 'NODE_JS' },
  { id: 9, postStack: 'SQL' },
  { id: 10, postStack: 'DBMS_RDBMS' },
  { id: 11, postStack: 'REDIS' },
  { id: 12, postStack: 'POSTGRE_SQL' },
  { id: 13, postStack: 'REACT' },
  { id: 14, postStack: 'REACT_NATIVE' },
  { id: 15, postStack: 'VUE' },
  { id: 16, postStack: 'TYPE_SCRIPT' },
  { id: 17, postStack: 'NEXT_JS' },
  { id: 18, postStack: 'SVELTE' },
  { id: 19, postStack: 'KUBERNETES' },
  { id: 20, postStack: 'JENKINS' },
  { id: 21, postStack: 'GITHUB_ACTION' },
  { id: 22, postStack: 'HARBOR' },
  { id: 23, postStack: 'JAVA' },
  { id: 24, postStack: 'JAVA_SCRIPT' },
  { id: 25, postStack: 'RUBY' },
  { id: 26, postStack: 'AWS' },
  { id: 27, postStack: 'GO' },
  { id: 28, postStack: 'RUST' },
  { id: 29, postStack: 'KAFKA' },
  { id: 30, postStack: 'MYSQL' },
  { id: 31, postStack: 'MONGODB' },
  { id: 32, postStack: 'MARIA' },
  { id: 33, postStack: 'ORACLE' },
  { id: 34, postStack: 'MSA' },
  { id: 35, postStack: 'DOCKER' },
];
